In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)

In [3]:
my_list = list(range(1_000_000))

In [4]:
%timeit my_arr2 = my_arr*2

3.78 ms ± 97.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit my_list2 = [ x * 2 for x in my_list ]

148 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
data = np.array([[1.5,-0.1,3],[0,-3,6.5]]) 
#le estoy pasando una lista de listas
# si o si, los elementos de la lista 'externa' tienen que ser del mismo tipo, en este
#caso, son listas

In [11]:
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [12]:
data.shape, data.dtype

((2, 3), dtype('float64'))

In [13]:
#esta es buenisima, podes crear arrays del size que le pases
# sin tener que hacer list comprehension
np.zeros(3),np.ones(2),np.empty(5), np.arange(4)

(array([0., 0., 0.]),
 array([1., 1.]),
 array([1.5, 0.1, 3. , 3. , 6.5]),
 array([0, 1, 2, 3]))

In [21]:
np.identity(4), np.eye(4) # que diferencia hay????

(array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))